spring.application.name=api-gateway
server.port=8080

spring.config.import=optional:configserver:http://localhost:8888/
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ROUTE (clean format)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1